# -*- coding: utf-8 -*-
"""Enes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xG73G3-sgHLOP1BkSeDrP1A8Wo0O9ItC
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import pandas as pd
import scipy.stats as stats
import time
import itertools
from torch.utils.data import DataLoader, Dataset






class CausalDualExpert(nn.Module):
    """
    Combines a Statistical (Linear) view and a Structural (Non-Linear) view
    to determine the score for a specific causal class.
    """
    def __init__(self, cnn_dim, stat_dim, hidden_dim):
        super().__init__()

        # Expert A: The Statistician (Sees Pearson, Skew, Kurtosis)
        self.linear_expert = nn.Sequential(
            nn.Linear(stat_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Linear(hidden_dim // 2, 1)
        )

        # Expert B: The Visionary (Sees CNN Motif Features)
        self.nonlinear_expert = nn.Sequential(
            nn.Linear(cnn_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.LeakyReLU(0.2),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.LeakyReLU(0.2),
            nn.Linear(hidden_dim // 2, 1)
        )

        # Learnable Gate: Balances the importance of Linear vs Non-Linear for this class
        self.consensus_weight = nn.Parameter(torch.ones(1) * 0.5)

    def forward(self, cnn_feats, stat_feats):
        l_logit = self.linear_expert(stat_feats)
        nl_logit = self.nonlinear_expert(cnn_feats)

        # Weight the two opinions
        w = torch.sigmoid(self.consensus_weight)
        return (w * l_logit) + ((1 - w) * nl_logit)
class NeuralTripletProber(nn.Module):
    def __init__(self, h=128):
        super().__init__()

        # --- 1. SHARED FEATURE EXTRACTION ---
        # Scans the 3-node sequence for non-linear "textures"
        self.motif_scanner = nn.Sequential(
            nn.Conv1d(3, h, 3, padding=1), nn.BatchNorm1d(h), nn.LeakyReLU(0.2),
            nn.Conv1d(h, h, 3, padding=2, dilation=2), nn.BatchNorm1d(h), nn.LeakyReLU(0.2),
            nn.Conv1d(h, h, 1), nn.BatchNorm1d(h), nn.AdaptiveAvgPool1d(1)
        )

        # --- 2. THE CAUSAL COMMITTEES ---
        # Each class has its own Linear/Non-Linear dual expert
        # stat_dim = 9 (3 Corrs, 3 Skew, 3 Kurtosis)
        expert_cfg = (h, 9, h // 2)

        self.class_0 = CausalDualExpert(*expert_cfg) # Independence
        self.class_1 = CausalDualExpert(*expert_cfg) # Chain
        self.class_2 = CausalDualExpert(*expert_cfg) # Fork
        self.class_3 = CausalDualExpert(*expert_cfg) # Collider
        self.class_4 = CausalDualExpert(*expert_cfg) # Asymmetric/Invalid

    # --- THE SPINE (DAG & Pearson Constraints) ---
    def get_triplet_adjacency(self, logits):
        probs = torch.softmax(logits, dim=-1)
        W = torch.zeros((logits.shape[0], 3, 3), device=logits.device)
        # Mapping logits to a 3x3 adjacency matrix
        W[:, 0, 1] = probs[:, 1] + probs[:, 3] # x->y in Chain(1) or Collider(3)
        W[:, 1, 2] = probs[:, 1] + probs[:, 2] # y->z in Chain(1) or Fork(2)
        W[:, 1, 0] = probs[:, 2] + probs[:, 4] # y->x in Fork(2) or Asym(4)
        W[:, 2, 1] = probs[:, 3] + probs[:, 4] # z->y in Collider(3) or Asym(4)
        return W

    def compute_topological_penalty(self, W):
        d = 3
        W_sq = W * W
        I = torch.eye(d, device=W.device).unsqueeze(0)
        M = I + W_sq / d
        E = torch.matrix_power(M, d) # Trace(E) - d = 0 implies acyclicity
        return (torch.diagonal(E, dim1=-2, dim2=-1).sum(-1) - d).mean()

    def compute_pearson_penalty(self, logits, corrs):
        probs = torch.softmax(logits, dim=-1)
        prob_exists = 1.0 - probs[:, 0] # 1 - P(Independence)
        avg_corr = torch.abs(corrs).mean(dim=-1)
        return (prob_exists * (1.0 - avg_corr)).mean()

    # --- FORWARD PASS ---
    def forward(self, x):
        # 1. Structural Branch (CNN)
        cnn_feats = self.motif_scanner(x).squeeze(-1)

        # 2. Statistical Branch (Math)
        m = x.mean(dim=-1, keepdim=True)
        s = x.std(dim=-1, unbiased=False, keepdim=True) + 1e-8
        z = (x - m) / s
        skew = (z ** 3).mean(dim=-1)
        kurt = (z ** 4).mean(dim=-1) - 3.0

        # Calculate Pearson Matrix
        x_n = x - m
        cov = torch.matmul(x_n, x_n.transpose(1, 2)) / (x.shape[-1] - 1)
        corr_mat = cov / (torch.matmul(s, s.transpose(1, 2)) + 1e-8)
        corrs = torch.stack([corr_mat[:,0,1], corr_mat[:,0,2], corr_mat[:,1,2]], dim=-1)

        stat_feats = torch.cat([skew, kurt, corrs], dim=-1)

        # 3. Decision Layer (Ensemble Voting)
        logits = torch.cat([
            self.class_0(cnn_feats, stat_feats),
            self.class_1(cnn_feats, stat_feats),
            self.class_2(cnn_feats, stat_feats),
            self.class_3(cnn_feats, stat_feats),
            self.class_4(cnn_feats, stat_feats)
        ], dim=-1)

        # 4. Multi-Objective Penalties
        W = self.get_triplet_adjacency(logits)
        topo_p = self.compute_topological_penalty(W)
        pearson_p = self.compute_pearson_penalty(logits, corrs)

        total_p = (1.0 * topo_p) + (1.0 * pearson_p)

        return logits, total_p











# ==========================================
# 1. BIOLOGICAL MOTIF GENERATOR (NOISY NON-LINEAR SEM)
# ==========================================
class TripletDataset(Dataset):
    def __init__(self, n_samples=20000, seq_len=1000, latent_dim=4):
        self.seq_len = seq_len
        self.latent_dim = latent_dim
        self.data, self.labels = self._generate_sota_data(n_samples)

    def _biochemical_noise(self, size):
        """ SOTA: Non-Gaussian, Heavy-tailed noise (Protein concentrations are rarely Normal) """
        # Mix of Log-Normal and Gumbel to simulate bursty gene expression
        noise = np.exp(np.random.normal(0, 0.3, size)) - 1.0
        return (noise - np.mean(noise)) / (np.std(noise) + 1e-8)

    def _sota_link(self, p, coupling_strength=None):
        p_norm = (p - np.mean(p)) / (np.std(p) + 1e-8)
        strength = coupling_strength if coupling_strength else np.random.uniform(0.8, 2.5)

        mode = np.random.choice(['hill', 'michaelis', 'sigmoid', 'softplus'])

        if mode == 'hill':
            n = np.random.uniform(2, 5)
            # SOTA FIX: Use absolute value for the power, then restore the sign
            p_abs = np.abs(p_norm)
            resp = strength * (p_abs**n) / (1.0**n + p_abs**n + 1e-8)
            resp = resp * np.sign(p_norm) # Restore directional logic

        elif mode == 'michaelis':
            # Michaelis-Menten is naturally robust to negatives if using abs()
            resp = strength * p_norm / (0.5 + np.abs(p_norm))

        elif mode == 'sigmoid':
            # Sigmoid is numerically stable for all real numbers
            resp = strength * (1 / (1 + np.exp(-3.0 * p_norm)))

        else: # softplus
            # Approximates ReLU but differentiable (SOTA for neural SEMs)
            resp = np.log(1 + np.exp(p_norm * strength))

        # Add Heteroscedastic noise (Shot Noise)
        noise = self._biochemical_noise(self.seq_len)
        shot_noise_scale = 0.1 * np.abs(resp)
        return resp + (noise * (1.0 + shot_noise_scale))

    def _generate_sota_data(self, n_samples):
        D, L = [], []
        # Increase variety of per-run variations
        iters = n_samples // 120

        for _ in range(iters):
            # U is a global latent context (e.g. cell size/state) affecting all downstream
            u_global = self._biochemical_noise(self.seq_len)

            s = lambda: self._biochemical_noise(self.seq_len)

            # --- CLASS 0: Independent (Baseline) ---
            D.append(np.stack([s(), s(), s()])); L.append(0)

            # --- CLASS 1: Chain (X -> Y -> Z) ---
            # SOTA: We use the latent U to create "Partial Confounding" -
            # This forces the model to find the direct path through the shared noise.
            x1 = s() + 0.2*u_global
            y1 = self._sota_link(x1) + 0.2*u_global
            z1 = self._sota_link(y1) + 0.2*u_global
            D.append(np.stack([x1, y1, z1])); L.append(1)

            # --- CLASS 2: Fork (X <- Y -> Z) ---
            y2 = s() + 0.5*u_global
            x2 = self._sota_link(y2)
            z2 = self._sota_link(y2)
            D.append(np.stack([x2, y2, z2])); L.append(2)

            # --- CLASS 3: Collider (X -> Y <- Z) ---
            # High Signal-to-Noise ratio for the Y integration
            x3, z3 = s(), s()
            y3 = self._sota_link(x3, 1.2) + self._sota_link(z3, 1.2)
            D.append(np.stack([x3, y3, z3])); L.append(3)

            # --- CLASS 4: SOTA Latent Confounder (X <- U -> Z) ---
            # No direct edge between X and Z, but they share a powerful hidden cause.
            # This is the 'hallucination trap'.
            u_hidden = s()
            x4 = self._sota_link(u_hidden)
            z4 = self._sota_link(u_hidden)
            y4_rand = s()
            D.append(np.stack([x4, y4_rand, z4])); L.append(4)

            # --- CLASS 5: Selection Bias (M-Structure) ---
            # X and Z are independent, but both influence a HIDDEN variable.
            # This tests if the model mistakenly orients edges due to selection.
           #nd(np.stack([x5, y5_rand, z5])); L.append(5)

        return torch.tensor(np.array(D), dtype=torch.float32), torch.tensor(L, dtype=torch.long)

    def __len__(self): return len(self.labels)
    def __getitem__(self, i):
        # SOTA normalization: Instance Norm (Z-score per triplet)
        x = self.data[i]
        x = (x - x.mean(dim=-1, keepdim=True)) / (x.std(dim=-1, keepdim=True) + 1e-8)
        return x, self.labels[i]
# ==========================================
# 2. DILATED NEURAL PROBER ARCHITECTURE
# ==========================================

# ==========================================
# 3. ENGINES & DISCOVERY LOGIC
# ==========================================
def get_neural_asymmetry_score(i, j, X_working, model, device):
    d = X_working.shape[1]
    votes_ij, votes_ji = 0.0, 0.0
    model.eval() # Ensure dropout/batchnorm are in eval mode
    with torch.no_grad():
        for k in range(d):
            if k == i or k == j: continue

            # Helper to get probs from the new dual-return forward
            def get_probs(nodes):
                trip = torch.tensor(X_working[:, nodes].T, dtype=torch.float32).unsqueeze(0).to(device)
                trip = (trip - trip.mean(-1, keepdim=True)) / (trip.std(-1, keepdim=True) + 1e-8)
                logits, _ = model(trip) # Unpack and ignore the penalty (_)
                return F.softmax(logits, dim=-1).squeeze(0)

            probs = get_probs([i, j, k])
            probs_rev = get_probs([j, i, k])

            # Logic: Chain/Collider indicators minus the "Independence/Noise" class (4)
            votes_ij += (probs[1].item() + probs[3].item() + probs_rev[2].item()) - (probs[4].item() + probs_rev[4].item())
            votes_ji += (probs[2].item() + probs_rev[1].item() + probs_rev[3].item()) - (probs[4].item() + probs_rev[4].item())

    return -votes_ij, -votes_ji

def find_triplets(X_obs, d):
    v_structs = []
    for y in range(d):
        for x in range(d):
            for z in range(x + 1, d):
                if x == y or y == z: continue
                r_xy = abs(np.corrcoef(X_obs[:, x], X_obs[:, y])[0, 1])
                r_yz = abs(np.corrcoef(X_obs[:, y], X_obs[:, z])[0, 1])
                r_xz = abs(np.corrcoef(X_obs[:, x], X_obs[:, z])[0, 1])
                denom = np.sqrt((1 - r_xy**2) * (1 - r_yz**2)) + 1e-8
                pcorr_xz_y = (r_xz - r_xy * r_yz) / denom
                if r_xz > 0.15 and r_yz > 0.15 and r_xy < 0.1 and abs(pcorr_xz_y) > 0.15:
                    v_structs.append((abs(pcorr_xz_y), x, z, y))
    return v_structs

def layered_causal_discovery_neural(X_obs, d, model, device, max_edges=17):
    W_pred = np.zeros((d, d))
    X_working = X_obs.copy()
    edges_count = 0
    v_structs = find_triplets(X_obs, d)
    v_structs.sort(key=lambda x: x[0], reverse=True)
    for _, u, v, w in v_structs:
        if edges_count < max_edges - 1:
            if W_pred[v, u] == 0 and W_pred[v, w] == 0:
                W_pred[u, v], W_pred[w, v] = 1, 1
                edges_count += 2
    model.eval()
    while edges_count < max_edges:
        best_pair, max_sim = None, -np.inf
        for i in range(d):
            for j in range(d):
                if i == j or W_pred[i, j] == 1 or W_pred[j, i] == 1: continue
                sim = abs(np.corrcoef(X_working[:, i], X_working[:, j])[0, 1])
                if sim > max_sim and sim > 0.08:
                    s_ij, s_ji = get_neural_asymmetry_score(i, j, X_working, model, device)
                    if s_ij < s_ji: max_sim, best_pair = sim, (i, j)
        if not best_pair: break
        u, v = best_pair
        W_pred[u, v] = 1
        edges_count += 1
        slope, intercept, _, _, _ = stats.linregress(X_working[:, u], X_working[:, v])
        X_working[:, v] -= (slope * X_working[:, u] + intercept)
        X_working[:, v] = (X_working[:, v] - np.mean(X_working[:, v])) / (np.std(X_working[:, v]) + 1e-8)

        W_refined = post_prune_graph(W_pred, X_obs, threshold=0.12)

    return W_refined

def fast_pearson_discovery(X_obs, d, max_edges=17):
    W_pred = np.zeros((d, d))
    corr_matrix = np.abs(np.corrcoef(X_obs.T))
    np.fill_diagonal(corr_matrix, 0)
    flat_indices = np.argsort(corr_matrix, axis=None)[::-1]
    for idx in flat_indices[:max_edges]:
        u, v = np.unravel_index(idx, corr_matrix.shape)
        if W_pred[v, u] == 0: W_pred[u, v] = 1
    return W_pred

# ==========================================
# 4. UTILS & METRICS
# ==========================================
def calculate_metrics(W_pred, W_true):
    TP = np.sum((W_pred != 0) & (W_pred == W_true))
    p = TP / np.sum(W_pred != 0) if np.sum(W_pred != 0) > 0 else 0
    r = TP / np.sum(W_true != 0) if np.sum(W_true != 0) > 0 else 0
    f1 = 2 * p * r / (p + r) if (p + r) > 0 else 0
    shd = np.sum(W_pred != W_true)
    return p, r, f1, shd

def generate_sachs_obs(df, n_obs=2000):
    d = 11
    sampled = df.sample(n=n_obs, replace=True).values
    X = (sampled - np.mean(sampled, axis=0)) / (np.std(sampled, axis=0) + 1e-8)
    W_true = np.zeros((d, d))
    edges = [(8, 7), (8, 10), (8, 9), (8, 0), (8, 1), (7, 0), (7, 1), (7, 5), (7, 6), (7, 9), (7, 10), (0, 1), (1, 5), (2, 3), (4, 3), (4, 2), (4, 6)]
    for i, j in edges: W_true[i, j] = 1
    return X, W_true

# ==========================================
# 5. EXECUTION LOOP
# ==========================================

def get_partial_correlation(X, i, j, k):
    """Calculates partial correlation of i and j given k."""
    rho = np.corrcoef(X[:, [i, j, k]].T)
    r_ij = rho[0, 1]
    r_ik = rho[0, 2]
    r_jk = rho[1, 2]

    numerator = r_ij - (r_ik * r_jk)
    denominator = np.sqrt((1 - r_ik**2) * (1 - r_jk**2)) + 1e-8
    return numerator / denominator

def post_prune_graph(W_pred, X_obs, threshold=0.1):
    """
    Identifies and removes indirect edges in the predicted graph.
    If X -> Y exists, but partial_corr(X, Y | Z) is low,
    it implies the link is likely X -> Z -> Y or spurious.
    """
    W_pruned = W_pred.copy()
    d = W_pruned.shape[0]

    # Iterate over all detected edges
    edges = np.argwhere(W_pruned > 0)
    for u, v in edges:
        # Check every other node k as a potential mediator
        for k in range(d):
            if k == u or k == v:
                continue

            # We only test k if it has some relationship with the pair
            p_corr = abs(get_partial_correlation(X_obs, u, v, k))

            # If correlation drops significantly, prune the edge
            if p_corr < threshold:
                W_pruned[u, v] = 0
                break # Move to next edge

    return W_pruned



def layered_causal_discovery_neural(X_obs, d, model, device, max_edges=17):
    W_pred = np.zeros((d, d))
    X_working = X_obs.copy()
    edges_count = 0
    v_structs = find_triplets(X_obs, d)
    v_structs.sort(key=lambda x: x[0], reverse=True)
    for _, u, v, w in v_structs:
        if edges_count < max_edges - 1:
            if W_pred[v, u] == 0 and W_pred[v, w] == 0:
                W_pred[u, v], W_pred[w, v] = 1, 1
                edges_count += 2
    model.eval()
    while edges_count < max_edges:
        best_pair, max_sim = None, -np.inf
        for i in range(d):
            for j in range(d):
                if i == j or W_pred[i, j] == 1 or W_pred[j, i] == 1: continue
                sim = abs(np.corrcoef(X_working[:, i], X_working[:, j])[0, 1])
                if sim > max_sim and sim > 0.08:
                    s_ij, s_ji = get_neural_asymmetry_score(i, j, X_working, model, device)
                    if s_ij < s_ji: max_sim, best_pair = sim, (i, j)
        if not best_pair: break
        u, v = best_pair
        W_pred[u, v] = 1
        edges_count += 1
        slope, intercept, _, _, _ = stats.linregress(X_working[:, u], X_working[:, v])
        X_working[:, v] -= (slope * X_working[:, u] + intercept)
        X_working[:, v] = (X_working[:, v] - np.mean(X_working[:, v])) / (np.std(X_working[:, v]) + 1e-8)

        W_refined = post_prune_graph(W_pred, X_obs, threshold=0.12)

    return W_refined

if __name__ == "__main__":
    url = "https://www.bnlearn.com/book-crc/code/sachs.data.txt.gz"
    sachs_df = pd.read_csv(url, sep=r'\s+')
    device = "cuda" if torch.cuda.is_available() else "cpu"

    for i in range(10):
        # 1. Train Prober
        model = NeuralTripletProber().to(device)
        optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
        loader = DataLoader(TripletDataset(n_samples=150000), batch_size=128, shuffle=True)

        print(f"\n[{i+1}/10] Training Neural Triplet Prober...")
        for epoch in range(3):
            model.train()
            epoch_loss = 0
            for x, y in loader:
                optimizer.zero_grad()

                # UNPACK: forward() now returns (logits, total_p)
                logits, physics_penalty = model(x.to(device))

                # 1. Primary Classification Loss (Supervised Labels)
                ce_loss = F.cross_entropy(logits, y.to(device))

                # 2. Total Loss = Supervised + Physics-Informed Penalties
                # This forces the CNN to respect DAG topology and Pearson alignment
                loss = ce_loss + physics_penalty

                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()

            print(f"Epoch {epoch+1}/3 | Avg Loss: {epoch_loss/len(loader):.4f}")
        # 2. Results Containers
        results_p, results_n, results_int, results_uni = [], [], [], []
        start = time.time()

        for trial in range(1):
            X, W_true = generate_sachs_obs(sachs_df, n_obs=10000)

            # Individual Engine Runs
            W_fast = fast_pearson_discovery(X, 11)
            W_robust = layered_causal_discovery_neural(X, 11, model, device)

            # Consensus Sets
            W_inter = np.logical_and(W_fast, W_robust).astype(float)
            W_union = np.logical_or(W_fast, W_robust).astype(float)

            results_p.append(calculate_metrics(W_fast, W_true))
            results_n.append(calculate_metrics(W_robust, W_true))
            results_int.append(calculate_metrics(W_inter, W_true))
            results_uni.append(calculate_metrics(W_union, W_true))

        def print_res(name, res_list):
            metrics = [np.mean([r[j] for r in res_list]) for j in range(4)]
            print(f"{name:<18} | Prec: {metrics[0]:.4f} | Rec: {metrics[1]:.4f} | F1: {metrics[2]:.4f} | SHD: {metrics[3]:.2f}")

        print(f"\n=== SEPARATED RESULTS (Avg over 2 trials) ===")
        print_res("Fast Linear (P)", results_p)
        print_res("Robust Neural", results_n)
        print("-" * 65)
        print_res("Intersection", results_int)
        print_res("Union", results_uni)
        print(f"Trial Elapsed: {time.time()-start:.2f}s")